apiVersion: v1
kind: ImageStream
metadata:
  name: fis-java-openshift
spec:
  dockerImageRepository: registry.access.redhat.com/jboss-fuse-6/fis-java-openshift
  tags:
  - name: "2.0"
    annotations:
      description: JBoss Fuse Integration Services 2.0 Java S2I images.
      iconClass: icon-jboss
      supports: jboss-fuse:6.3.0,java:8,xpaas:1.2
      tags: builder,jboss-fuse,java,xpaas
      version: "2.0"