---
kind: Template
apiVersion: v1
metadata:
  name: gateway
labels:
  template: gateway
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: gateway
    labels:
      application: gateway
  spec:
    replicas: 1
    selector:
      deploymentconfig: gateway
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          application: gateway
          deploymentconfig: gateway
        name: gateway
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: library/gateway:latest
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 180
          name: gateway
          ports:
          - containerPort: 8778
            name: jolokia
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
          resources: {}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - gateway
        from:
          kind: ImageStreamTag
          name: gateway:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: gateway
      application: gateway
      hystrix.enabled: "true"
    name: gateway
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: gateway
- apiVersion: v1
  kind: Route
  metadata:
    name: gateway
    labels:
      application: gateway
  spec:
    to:
      kind: Service
      name: gateway